apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/backend-default: "true"
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: ConnectionString
              value: Username=postgres;Password=password;Server=db;Port=5432;Database=postgres;SearchPath=viatabloid
          image: backend:v2
          name: backend
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              hostPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: backend
  type: NodePort