version: '3.8'
services:
  db:
    build: 
      context: ./
      dockerfile: DB/Dockerfile
    restart: always
    container_name: "db"
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  
  backend:
    image: 'backend:latest'
    build: 
      context: ./
      dockerfile: DB/Dockerfile
    container_name: "backend"
    ports:
      - 7112:7112
    depends_on:
      - db
volumes:
  db:
    driver: local